/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafico;

import java.applet.AudioClip;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author leonardo
 */
public class Portada extends javax.swing.JFrame {

    /**
     * Creates new form Portada
     */
    public Portada() {
        initComponents();
        this.setLocationRelativeTo(null);
        lbl_continuar.setVisible(false);
        imagenes();
        cursores();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/log.png")).getImage());
    }
    private int x,y;
    private AudioClip sonidoc,sonidos,sonidom,sonidoss;
    private void cursores(){
        Cursor cursor;
        ImageIcon imagen=new ImageIcon(getClass().getResource("/cursores/cflecha.png"));
        Toolkit t=Toolkit.getDefaultToolkit();
        cursor=t.createCustomCursor(imagen.getImage(), new Point(1,1), "cursor");
        setCursor(cursor);
    }
    private void imagenes(){
        ImageIcon ipn=new ImageIcon(getClass().getResource("/imagenes/ipn.png"));
        Icon imagen1=new ImageIcon(ipn.getImage().getScaledInstance(lbl_escudoIpn.getWidth(), lbl_escudoIpn.getHeight(), Image.SCALE_DEFAULT));
        lbl_escudoIpn.setIcon(imagen1);
        lbl_escudoIpn.setOpaque(false);
        this.repaint();
        ImageIcon upiicsa=new ImageIcon(getClass().getResource("/imagenes/upiicsa.png"));
        Icon imagen2=new ImageIcon(upiicsa.getImage().getScaledInstance(lbl_escudoUpiicsa.getWidth(), lbl_escudoUpiicsa.getHeight(), Image.SCALE_DEFAULT));
        lbl_escudoUpiicsa.setIcon(imagen2);
        lbl_escudoUpiicsa.setOpaque(false);
        this.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_minimizar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        lbl_encabezado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_escudoIpn = new javax.swing.JLabel();
        lbl_escudoUpiicsa = new javax.swing.JLabel();
        lbl_ipn = new javax.swing.JLabel();
        lbl_upiicsa1 = new javax.swing.JLabel();
        lbl_upiicsa2 = new javax.swing.JLabel();
        lbl_upiicsa3 = new javax.swing.JLabel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_equipo = new javax.swing.JLabel();
        lbl_integrantes = new javax.swing.JLabel();
        lbl_nombre1 = new javax.swing.JLabel();
        lbl_nombre2 = new javax.swing.JLabel();
        lbl_nombre3 = new javax.swing.JLabel();
        lbl_nombre4 = new javax.swing.JLabel();
        lbl_nombre5 = new javax.swing.JLabel();
        btn_continuar = new javax.swing.JButton();
        lbl_continuar = new javax.swing.JLabel();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(810, 523));
        setMinimumSize(new java.awt.Dimension(810, 523));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_minimizar.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        btn_minimizar.setForeground(new java.awt.Color(255, 255, 255));
        btn_minimizar.setText("-");
        btn_minimizar.setToolTipText("Minimizar");
        btn_minimizar.setBorder(null);
        btn_minimizar.setBorderPainted(false);
        btn_minimizar.setContentAreaFilled(false);
        btn_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_minimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_minimizarMouseExited(evt);
            }
        });
        btn_minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minimizarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 30, 20));

        btn_salir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setText("x");
        btn_salir.setToolTipText("Cerrar");
        btn_salir.setBorder(null);
        btn_salir.setBorderPainted(false);
        btn_salir.setContentAreaFilled(false);
        btn_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_salirMouseExited(evt);
            }
        });
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, 20));

        lbl_encabezado.setBackground(new java.awt.Color(0, 190, 32));
        lbl_encabezado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_encabezado.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_encabezado.setText("Portada");
        lbl_encabezado.setOpaque(true);
        lbl_encabezado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbl_encabezadoMouseDragged(evt);
            }
        });
        lbl_encabezado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_encabezadoMousePressed(evt);
            }
        });
        jPanel1.add(lbl_encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 810, 50);

        jPanel2.setBackground(new java.awt.Color(248, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(810, 523));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_escudoIpn.setOpaque(true);
        jPanel2.add(lbl_escudoIpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 110));

        lbl_escudoUpiicsa.setOpaque(true);
        jPanel2.add(lbl_escudoUpiicsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 160, 110));

        lbl_ipn.setFont(new java.awt.Font("Antique-Olive-Bold", 0, 30)); // NOI18N
        lbl_ipn.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ipn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ipn.setText("Instituto Politécnico Nacional");
        lbl_ipn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl_ipn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 450, -1));

        lbl_upiicsa1.setFont(new java.awt.Font("Antique-Olive-Normal", 0, 26)); // NOI18N
        lbl_upiicsa1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_upiicsa1.setText("Unidad Profesional de Interdisciplinaria");
        lbl_upiicsa1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl_upiicsa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 460, 40));

        lbl_upiicsa2.setFont(new java.awt.Font("Antique-Olive-Normal", 0, 26)); // NOI18N
        lbl_upiicsa2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_upiicsa2.setText("de Ingeniería y Ciencias Sociales y");
        jPanel2.add(lbl_upiicsa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        lbl_upiicsa3.setFont(new java.awt.Font("Antique-Olive-Normal", 0, 26)); // NOI18N
        lbl_upiicsa3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_upiicsa3.setText("Administrativas");
        jPanel2.add(lbl_upiicsa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        lbl_titulo.setFont(new java.awt.Font("Apple Garamond Light", 1, 30)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setText("Convertidor de medidas");
        jPanel2.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        lbl_equipo.setFont(new java.awt.Font("AvantGarde Bk BT", 0, 26)); // NOI18N
        lbl_equipo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_equipo.setText("Equipo no. 6");
        jPanel2.add(lbl_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        lbl_integrantes.setFont(new java.awt.Font("AvantGarde Bk BT", 0, 26)); // NOI18N
        lbl_integrantes.setForeground(new java.awt.Color(255, 255, 255));
        lbl_integrantes.setText("Integrantes:");
        jPanel2.add(lbl_integrantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        lbl_nombre1.setFont(new java.awt.Font("AvantGarde Bk BT", 0, 26)); // NOI18N
        lbl_nombre1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre1.setText("CALVILLO TAPIA LEONARDO");
        jPanel2.add(lbl_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        lbl_nombre2.setFont(new java.awt.Font("AvantGarde Bk BT", 0, 26)); // NOI18N
        lbl_nombre2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre2.setText("GARCÍA HERNÁNDEZ ARMANDO");
        jPanel2.add(lbl_nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        lbl_nombre3.setFont(new java.awt.Font("AvantGarde Bk BT", 0, 26)); // NOI18N
        lbl_nombre3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre3.setText("RAMÍREZ LÓPEZ ALEJANDRO");
        jPanel2.add(lbl_nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        lbl_nombre4.setFont(new java.awt.Font("AvantGarde Bk BT", 0, 26)); // NOI18N
        lbl_nombre4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre4.setText("JÍMENEZ PANIAGUA ALDO");
        jPanel2.add(lbl_nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        lbl_nombre5.setFont(new java.awt.Font("AvantGarde Bk BT", 0, 26)); // NOI18N
        lbl_nombre5.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre5.setText("VALLEJO MARTÍNEZ ALAN ROMAN");
        jPanel2.add(lbl_nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        btn_continuar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_continuar.setForeground(new java.awt.Color(255, 255, 255));
        btn_continuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/70.png"))); // NOI18N
        btn_continuar.setBorder(null);
        btn_continuar.setBorderPainted(false);
        btn_continuar.setContentAreaFilled(false);
        btn_continuar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_continuar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/75.png"))); // NOI18N
        btn_continuar.setVerifyInputWhenFocusTarget(false);
        btn_continuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_continuarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_continuarMouseExited(evt);
            }
        });
        btn_continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_continuarActionPerformed(evt);
            }
        });
        btn_continuar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_continuarKeyPressed(evt);
            }
        });
        jPanel2.add(btn_continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 100, 70));

        lbl_continuar.setFont(new java.awt.Font("Annfold", 0, 24)); // NOI18N
        lbl_continuar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_continuar.setText("Continuar");
        jPanel2.add(lbl_continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, -1, -1));

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/p2.gif"))); // NOI18N
        jPanel2.add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 480));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 50, 810, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minimizarActionPerformed
        this.setExtendedState(ICONIFIED);
        this.setExtendedState(1);
    }//GEN-LAST:event_btn_minimizarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void lbl_encabezadoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_encabezadoMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_lbl_encabezadoMouseDragged

    private void lbl_encabezadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_encabezadoMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lbl_encabezadoMousePressed

    private void btn_continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_continuarActionPerformed
        sonidoc= java.applet.Applet.newAudioClip(getClass().getResource("/audio/sublime.wav"));
        sonidoc.play();
        this.dispose();
        new Convertidor().setVisible(true);
    }//GEN-LAST:event_btn_continuarActionPerformed

    private void btn_continuarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_continuarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){this.dispose();
        new Convertidor().setVisible(true);
    }
    }//GEN-LAST:event_btn_continuarKeyPressed

    private void btn_continuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_continuarMouseEntered
        sonidoc= java.applet.Applet.newAudioClip(getClass().getResource("/audio/continuar.wav"));
        sonidoc.play();
        lbl_continuar.setVisible(true);
        Cursor mano;
        ImageIcon imagen=new ImageIcon(getClass().getResource("/cursores/cmano.png"));
        Toolkit t=Toolkit.getDefaultToolkit();
        mano=t.createCustomCursor(imagen.getImage(), new Point(1,1), "cursor");
        btn_continuar.setCursor(mano);
    }//GEN-LAST:event_btn_continuarMouseEntered

    private void btn_continuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_continuarMouseExited
        lbl_continuar.setVisible(false);
        sonidoc.stop();
    }//GEN-LAST:event_btn_continuarMouseExited

    private void btn_minimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizarMouseEntered
        sonidom= java.applet.Applet.newAudioClip(getClass().getResource("/audio/minimizar.wav"));
        sonidom.play();
        Cursor mano;
        ImageIcon imagen=new ImageIcon(getClass().getResource("/cursores/cmano.png"));
        Toolkit t=Toolkit.getDefaultToolkit();
        mano=t.createCustomCursor(imagen.getImage(), new Point(1,1), "cursor");
        btn_minimizar.setCursor(mano);
    }//GEN-LAST:event_btn_minimizarMouseEntered

    private void btn_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseEntered
        sonidos= java.applet.Applet.newAudioClip(getClass().getResource("/audio/cerrar.wav"));
        sonidos.play();
        Cursor mano;
        ImageIcon imagen=new ImageIcon(getClass().getResource("/cursores/cmano.png"));
        Toolkit t=Toolkit.getDefaultToolkit();
        mano=t.createCustomCursor(imagen.getImage(), new Point(1,1), "cursor");
        btn_salir.setCursor(mano);
    }//GEN-LAST:event_btn_salirMouseEntered

    private void btn_minimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizarMouseExited
        sonidom.stop();
    }//GEN-LAST:event_btn_minimizarMouseExited

    private void btn_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseExited
        sonidos.stop();
    }//GEN-LAST:event_btn_salirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Portada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_continuar;
    private javax.swing.JButton btn_minimizar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_continuar;
    private javax.swing.JLabel lbl_encabezado;
    private javax.swing.JLabel lbl_equipo;
    private javax.swing.JLabel lbl_escudoIpn;
    private javax.swing.JLabel lbl_escudoUpiicsa;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JLabel lbl_integrantes;
    private javax.swing.JLabel lbl_ipn;
    private javax.swing.JLabel lbl_nombre1;
    private javax.swing.JLabel lbl_nombre2;
    private javax.swing.JLabel lbl_nombre3;
    private javax.swing.JLabel lbl_nombre4;
    private javax.swing.JLabel lbl_nombre5;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_upiicsa1;
    private javax.swing.JLabel lbl_upiicsa2;
    private javax.swing.JLabel lbl_upiicsa3;
    // End of variables declaration//GEN-END:variables
}
