/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafico;

import java.applet.AudioClip;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author leonardo
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    
    public SplashScreen() {
        initComponents();
        cursores();
        sonido();
        imagen();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/log.png")).getImage());
        this.setLocationRelativeTo(null);
    }
    private void imagen(){
        ImageIcon logo=new ImageIcon(getClass().getResource("/imagenes/logo.png"));
        Icon imagen1=new ImageIcon(logo.getImage().getScaledInstance(lbl_logo.getWidth(), lbl_logo.getHeight(), Image.SCALE_DEFAULT));
        lbl_logo.setIcon(imagen1);
        lbl_logo.setOpaque(false);
        this.repaint();
    }
    private void sonido()
    {
        AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/audio/40y20.wav"));
        sonido.play();
    }    
    private void cursores(){
        Cursor cursor;
        ImageIcon imagen=new ImageIcon(getClass().getResource("/cursores/cflecha.png"));
        Toolkit t=Toolkit.getDefaultToolkit();
        cursor=t.createCustomCursor(imagen.getImage(), new Point(1,1), "Cursor");
        setCursor(cursor);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Jpb_login = new javax.swing.JProgressBar();
        lbl_porcentaje = new javax.swing.JLabel();
        lbl_copyright = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 383));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 204, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(750, 383));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 383));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jpb_login.setBackground(new java.awt.Color(102, 0, 0));
        Jpb_login.setForeground(new java.awt.Color(0, 204, 51));
        Jpb_login.setBorderPainted(false);
        jPanel1.add(Jpb_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 660, 40));

        lbl_porcentaje.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_porcentaje.setForeground(new java.awt.Color(255, 255, 255));
        lbl_porcentaje.setText("99%");
        jPanel1.add(lbl_porcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 90, 50));

        lbl_copyright.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_copyright.setForeground(new java.awt.Color(255, 255, 255));
        lbl_copyright.setText("© Convertidor de Medidas by equipo 06");
        jPanel1.add(lbl_copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        lbl_logo.setOpaque(true);
        jPanel1.add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 280, 180));

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/p1.jpg"))); // NOI18N
        jPanel1.add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar Jpb_login;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_copyright;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JLabel lbl_logo;
    public javax.swing.JLabel lbl_porcentaje;
    // End of variables declaration//GEN-END:variables
}
